@id=3522056f-a6a4-4b1f-b39d-48539e3094a7

PUT http://localhost:5028/orders/{{id}}
Content-Type: application/json

{
    "CustomerId": "1",
    "EmployeeId": "1",
    "OrderDate": "2024-07-20",
    "ShipperId": "1"
}